applications:
  - name: "Autodesk MotionBuilder"
    description: "Logiciel d'animation 3D en temps réel"
    category: "3D/Animation"
    icon: ""
    enabled: true
    has_versions: true
    default_version_index: 4
    versions:
      - name: "2026"
        version: "2026"
        methods:
          - type: "exe"
            url: "https://efulfillment.autodesk.com/NetSWDLD/2026/MOBPRO/8E8A1C2E-0952-3C68-842C-69A9FEB04127/SFX/Autodesk_MotionBuilder_2026_ML_Windows_64bit_dlm.sfx.exe"
            silent_args: "--mode unattended --accept_eula"
            priority: 1
      - name: "2025"
        version: "2025"
        methods:
          - type: "exe"
            url: "https://efulfillment.autodesk.com/NetSWDLD/2025/MOBPRO/8E8A1C2E-0952-3C68-842C-69A9FEB04127/SFX/Autodesk_MotionBuilder_2025_ML_Windows_64bit_dlm.sfx.exe"
            silent_args: "--mode unattended --accept_eula"
            priority: 1
      - name: "2024"
        version: "2024"
        methods:
          - type: "exe"
            url: "https://efulfillment.autodesk.com/NetSWDLD/2024/MOBPRO/8E8A1C2E-0952-3C68-842C-69A9FEB04127/SFX/Autodesk_MotionBuilder_2024_ML_Windows_64bit_dlm.sfx.exe"
            silent_args: "--mode unattended --accept_eula"
            priority: 1
      - name: "2023"
        version: "2023"
        methods:
          - type: "exe"
            url: "https://efulfillment.autodesk.com/NetSWDLD/2023/MOBPRO/8E8A1C2E-0952-3C68-842C-69A9FEB04127/SFX/Autodesk_MotionBuilder_2023_ML_Windows_64bit_dlm.sfx.exe"
            silent_args: "--mode unattended --accept_eula"
            priority: 1
      - name: "2022 LTS"
        version: "2022 (Recommandé)"
        methods:
          - type: "exe"
            url: "https://dds.autodesk.com/NetSWDLD/2022/MOBPRO/330EFCEA-0952-3C68-842C-69A9FEB04127/SFX/Autodesk_MB_2022_ML_Windows_64bit_dlm.sfx.exe"
            silent_args: "--mode unattended --accept_eula"
            priority: 1