applications:


  - name: "The Foundry Nuke"
    description: "Logiciel de composition et de montage pour les effets visuels"
    category: "3D/Animation"
    icon: ""
    enabled: true
    custom_install_path: true
    methods:
      - type: "msi"
        local_exe: "Nuke/Nuke15.1v3-win-x86_64.msi"
        silent_args: "/S /ACCEPT-FOUNDRY-EULA"
        priority: 1
        note: "Utilise installateur local - placez NukeStudio_installer.exe dans app/installers/"
